// Portfolio data constants - Akash Kumar Prasad

export const PERSONAL_INFO = {
  name: "Akash Kumar Prasad",
  shortName: "AKP",
  title: "AI Engineer & Full Stack Developer",
  tagline: "AI Engineering Intern @ Tectonic Agents | Founding Engineer @ RekZon",
  subtitle: "Architecting autonomous AI agents, enterprise RAG pipelines, and high-concurrency distributed systems across the digital cosmos.",
  bio: "I'm a final-year engineering student at MNNIT Allahabad, and I like building things people actually use. At Tectonic Agents, that means an AI agent that answers from real data and shows its sources. At RekZon, it's an AI recruiter that screens and interviews candidates. I care about software that's honest about what it knows: answers you can trace, numbers you can check. Away from work, I solve contest problems, over a thousand so far.",
  email: "akashkumarprasad9335@gmail.com",
  phone: "+91-7667841789",
  location: "Allahabad / Noida, India",
  resumeUrl: "/resume.pdf",
  github: "https://github.com/Akashkrp",
  linkedin: "https://linkedin.com/in/akash-kumar-prasad",
  status: "Available for High-Impact Roles & Founding Ventures",
};

export const TYPING_ROLES = [
  "AI Engineering Intern @ Tectonic Agents",
  "Founding Engineer @ RekZon",
  "AI & GenAI Systems Architect",
  "Full Stack Systems Engineer",
  "LeetCode Knight (1887 • 1000+ Solved)",
  "Codeforces Specialist (1416)",
];

export const HERO_STATS = [
  { label: "LeetCode Rating", value: "1887", sub: "Knight Tier" },
  { label: "Problems Solved", value: "1000+", sub: "DSA & Algorithmic Rigor" },
  { label: "Codeforces", value: "1416", sub: "Specialist Rank" },
];

export const EXPERIENCES = [
  {
    id: "tectonic",
    role: "AI Engineering Intern",
    company: "Tectonic Agents",
    badge: "Current",
    type: "LLM Agents for Engineering Data",
    period: "October 2026 - Present",
    location: "Bengaluru (Remote)",
    description: "Engineers need fast answers from dense technical data, and they can't use an AI that makes numbers up. I'm building a chat agent that answers from their own data and backs every figure with its source.",
    highlights: [
      "Developed an LLM-powered RAG chat agent in Python and FastAPI, using tool calling over structured engineering data.",
      "Implemented a hallucination-guard layer tracing every number and citation to sources, with 100+ automated pytest tests.",
      "Built REST and SSE streaming APIs and a JavaScript chat interface with caching, BM25 search, and source citation viewers.",
    ],
    tech: ["Python", "FastAPI", "RAG", "Tool Calling", "SSE Streaming", "BM25", "pytest", "JavaScript"],
    featured: true,
  },
  {
    id: "rekzon",
    role: "Founding Engineer",
    company: "RekZon",
    badge: "Entrepreneurial Venture",
    type: "AI Recruitment Platform",
    period: "2026 - Present",
    location: "Remote / Hybrid",
    description: "Screening candidates takes up weeks of a recruiter's time. As founding engineer, I built the AI that reads a job description, ranks candidates against it and runs the first interview by voice.",
    highlights: [
      "Engineered LLM-based JD-candidate matching, dynamically weighting extracted requirements to auto-score candidates with explainable rubrics.",
      "Built an interview evaluation pipeline using Deepgram STT + Claude Haiku 4.5 scoring for automated assessment and behavioral analysis.",
      "Engineered candidate enrichment pipeline using multiple waterfall providers, resolving deduplication & contact intelligence.",
      "Built vector search infrastructure using pgvector and Supabase, storing candidate embeddings for ultra-fast semantic JD matching.",
      "Architected an autonomous voice agent using Gemini 2.5 Flash for recruitment screening & auto-evaluating candidate responses in real time.",
    ],
    tech: ["Gemini 2.5 Flash", "Claude Haiku 4.5", "Deepgram STT", "pgvector", "Supabase", "LangChain", "Vector Search", "Python", "FastAPI"],
    featured: true,
  },
  {
    id: "freeflow",
    role: "Software Engineering Intern – Data & AI",
    company: "FreeFlow Advisors",
    badge: "Industry Production",
    type: "Data & AI Systems",
    period: "March 2026 - May 2026",
    location: "Noida, India",
    description: "Information about India's 250K+ educational institutions is scattered across inconsistent websites and documents. I built the pipelines that collect it, clean it into one reliable dataset and make it searchable.",
    highlights: [
      "Engineered concurrent web-scraping & OCR pipelines to aggregate data from 250K+ Indian educational institutions across heterogeneous sources.",
      "Built entity-resolution pipeline via LLM extraction, embeddings, and classification to normalize data across heterogeneous schemas.",
      "Developed semantic search & recommendation system via vector search & dense embeddings for personalized institutional discovery.",
    ],
    tech: ["Python", "OCR Pipelines", "Vector Search", "LLM Extraction", "Embeddings", "FastAPI", "Distributed Workers"],
    featured: true,
  },
];

export const EDUCATION_LIST = [
  {
    institution: "Motilal Nehru National Institute of Technology (MNNIT) Allahabad",
    degree: "Bachelor of Technology in Electronics and Communication Engineering",
    duration: "2023 - 2027",
    location: "Allahabad, Uttar Pradesh",
    highlights: [
      "Focusing on Core CS: Data Structures & Algorithms, Operating Systems, Computer Networks, DBMS, and OOP",
      "Active participant in technical societies, hackathons, and competitive programming clubs",
    ],
  },
  {
    institution: "D.A.V. Public School",
    degree: "Senior Secondary (CBSE - Class XII)",
    duration: "2022 - 2023",
    location: "Jamshedpur, Jharkhand",
    highlights: [
      "Majors in Physics, Chemistry, and Mathematics",
      "Strong foundation in algorithmic reasoning and scientific problem solving",
    ],
  },
  {
    institution: "D.A.V. Public School",
    degree: "Secondary (CBSE - Class X)",
    duration: "2020 - 2021",
    location: "Jamshedpur, Jharkhand",
    highlights: [
      "All-round academic excellence and computational science distinction",
    ],
  },
];

export const SKILL_CATEGORIES = [
  {
    category: "Languages",
    skills: ["C++", "C", "JavaScript", "TypeScript", "Python"],
  },
  {
    category: "AI / GenAI",
    skills: [
      "LLM Integration",
      "RAG Pipelines",
      "Prompt Engineering",
      "Structured Outputs",
      "LangChain",
      "Vector Embeddings",
      "Semantic Search",
      "HuggingFace",
      "Deepgram STT",
      "Gemini 2.5 Flash",
      "Claude Haiku 4.5",
    ],
  },
  {
    category: "Full-Stack & Backend",
    skills: [
      "React.js",
      "Node.js",
      "Express.js",
      "REST APIs",
      "WebSockets",
      "JWT Authentication",
      "Tailwind CSS",
      "Next.js",
      "HTML",
      "CSS",
    ],
  },
  {
    category: "Databases",
    skills: ["MongoDB", "MySQL", "PostgreSQL", "Pinecone", "pgvector (Supabase)"],
  },
  {
    category: "Infrastructure & Tools",
    skills: ["Docker", "Linux", "Git", "GitHub", "Postman", "VS Code", "Claude Code"],
  },
  {
    category: "Core CS",
    skills: [
      "Data Structures & Algorithms",
      "OOP",
      "DBMS",
      "Operating Systems",
      "Computer Networks",
      "Complexity Analysis",
    ],
  },
];

// Preserves existing projects (Clinico, Hirebotix, Medidose) and adds MahabharatGPT & StockLabs
export const PROJECTS = [
  {
    id: "mahabharat-gpt",
    title: "MahabharatGPT",
    subtitle: "Talk with the characters of the Mahabharata",
    category: "AI / GenAI",
    description: "Most chatbots answer questions about an epic. I wanted people to talk with the people in it. Pick Arjuna, Draupadi or any of 27 characters and ask them anything. They reply in first person, drawing only on what the source texts actually say.",
    tech: ["Python", "Flask", "LangChain", "Groq", "Pinecone", "Hugging Face Embeddings", "Docker", "NLP"],
    features: [
      "Reads 27 source books once, splits them into passages and indexes them so the right ones can be found instantly",
      "For each question, pulls the passages most relevant to that character while keeping the story they share with others",
      "The AI may only answer from those passages and shows which book each answer came from, so it stays true to the epic instead of inventing lore",
      "Packaged with Docker and hosted on Hugging Face, so anyone can try it in the browser",
    ],
    github: "https://github.com/Akashkrp",
    demo: "https://huggingface.co/spaces/Akashkrprasad/MahabharatGPT",
    image: "/projects/mahabharat-gpt.png",
    date: "2025",
    stats: "27 characters to talk to, every answer backed by the books it came from",
    featured: true,
  },
  {
    id: "stocklabs",
    title: "StockLabs",
    subtitle: "One live dashboard for prices, portfolio and market news",
    category: "Full Stack",
    description: "Investors juggle prices, holdings and news across different apps, and free tools often lag behind the market. StockLabs brings live prices, your real portfolio, market news and an AI assistant into one fast dashboard.",
    tech: ["React.js", "Express.js", "MongoDB", "WebSockets", "Upstox API", "YFinance API", "REST APIs"],
    features: [
      "Each user is sent live prices only for the stocks they watch, instead of everyone receiving everything, which cut update delay by 40%",
      "Connects to a real brokerage account through Upstox sign-in to show actual holdings",
      "An AI assistant reviews your portfolio, suggests stocks and answers market questions",
      "News from many financial feeds is collected and cached, so the news page loads instantly",
    ],
    github: "https://github.com/Akashkrp",
    demo: "https://stocklabs-r98d.onrender.com/",
    image: "/projects/stocklabs.png",
    date: "2025",
    stats: "Live price updates 40% faster, with AI insights on your own portfolio",
    featured: true,
  },
  {
    id: "clinico",
    title: "Clinico",
    subtitle: "Find a doctor, book a slot and pay online in a few clicks",
    category: "Full Stack",
    description: "Booking a clinic appointment still often means phone calls and waiting on hold. Clinico lets patients find a doctor by speciality, pick a time and pay online, while doctors and admins manage everything from their own dashboards.",
    tech: ["Node.js", "Express.js", "MongoDB", "React.js", "JWT", "Stripe", "Razorpay", "Cloudinary", "Mongoose"],
    features: [
      "Patients, doctors and admins each get their own experience and can only see and do what their role allows",
      "Appointment search was reworked to be 50% faster",
      "Payments through Stripe or Razorpay are verified before a booking is confirmed, and failed payments are handled cleanly",
      "A secure backend covers sign-in, bookings and payments end to end",
    ],
    github: "https://github.com/satyamgitsat2944/Clinico",
    demo: "https://clinico-frontend.onrender.com/",
    image: "/projects/clinico.png",
    date: "February 2025",
    stats: "Separate patient, doctor and admin experiences, with appointment search 50% faster",
    featured: true,
  },
  {
    id: "hirebotix",
    title: "Hirebotix",
    subtitle: "A job board that keeps employers and applicants in the loop",
    category: "Full Stack",
    description: "Applicants apply and then hear nothing back, while recruiters lose track of candidates across inboxes. Hirebotix gives employers one place to post roles and track every applicant, and keeps applicants updated automatically by email.",
    tech: ["MERN", "Cloudinary", "Redux Toolkit", "Nodemailer", "REST APIs"],
    features: [
      "Employers post jobs and move applicants through their hiring pipeline, and applicants get an email at each step",
      "Profile photos and resumes are stored and optimised in the cloud",
      "Data the app has already loaded is reused instead of fetched again, cutting network requests by 25%",
      "A clean, responsive interface that works on phone and desktop",
    ],
    github: "https://github.com/Akashkrp/HIREBOTIX",
    demo: "https://hirebotix-frontend.onrender.com/",
    image: "/projects/hirebotix.png",
    date: "November 2024",
    stats: "Applicants hear back at every step, and the app makes 25% fewer network requests",
    featured: true,
  },
  {
    id: "medidose",
    title: "Medidose",
    subtitle: "Reminders that help patients actually take their medicine",
    category: "AI / GenAI",
    description: "Patients on long treatments often miss doses, and nobody notices until it matters. Medidose reminds them on SMS and WhatsApp, tracks whether each dose was taken, and uses AI to flag patients who are at risk of falling off their plan.",
    tech: ["MERN", "Groq SDK", "Node-cron", "Twilio", "WhatsApp API"],
    features: [
      "Schedules a reminder for every dose and sends it over SMS and WhatsApp",
      "Reminders keep running even if the server restarts, so a dose is never silently skipped",
      "An AI model reviews each patient's history and flags those likely to miss doses",
      "Patients and caregivers can follow adherence and progress over time",
    ],
    github: "https://github.com/Akashkrp/MediDose",
    demo: "https://www.youtube.com/watch?v=QyM6PM0NbXg",
    date: "October 2025",
    stats: "Reminders where patients already are, plus an early warning for missed treatment",
    featured: false,
  },
  {
    id: "drowsiness-detection",
    title: "Drowsiness Detection System",
    subtitle: "Alerts drivers the moment they start to doze off",
    category: "Computer Vision",
    description: "Drowsy driving causes accidents that a timely alert could prevent. This system watches a driver's eyes through an ordinary webcam and sounds an alarm as soon as they begin to fall asleep.",
    tech: ["Python", "OpenCV", "dlib", "NumPy", "Pygame"],
    features: [
      "Finds the driver's face in every webcam frame and tracks 68 points around the eyes, nose and mouth",
      "Measures how open the eyes are, frame by frame",
      "Labels the driver Active, Drowsy or Sleeping based on how long the eyes stay closed",
      "Shows the live status on screen and plays an alarm when the driver is drowsy or asleep",
    ],
    github: "https://github.com/Akashkrp",
    demo: "https://github.com/Akashkrp",
    date: "",
    stats: "Works with any webcam and reacts in real time",
    featured: false,
  },
];

export const CODING_PROFILES = [
  {
    platform: "LeetCode",
    username: "Akp_23",
    tier: "Knight Tier",
    rating: 1887,
    problemsSolved: "1000+",
    url: "https://leetcode.com/u/Akp_23/",
    badge: "Top ~4% Globally",
    accent: "sky",
    highlight: "Knight Tier with 1000+ DSA problems solved and contest rating of 1887.",
  },
  {
    platform: "Codeforces",
    username: "Akash_krp",
    tier: "Specialist",
    rating: 1416,
    problemsSolved: "300+",
    url: "https://codeforces.com/profile/Akash_krp",
    badge: "Specialist Rank",
    accent: "violet",
    highlight: "Specialist on Codeforces with maximum rating of 1416 and 300+ competitive solutions.",
  },
];

export const ACHIEVEMENTS = [
  {
    id: 1,
    title: "Advitiya Hackathon (IIT Ropar)",
    rank: "Finalist (4th Position)",
    description: "Secured 4th position out of 130+ teams nationwide in Advitiya Hackathon at IIT Ropar.",
    date: "February 2025",
    category: "Hackathon",
    badge: "Top 3%",
  },
  {
    id: 2,
    title: "Smart India Hackathon (SIH)",
    rank: "Pre-finalist (Top 3)",
    description: "Pre-finalist and ranked among Top 3 in internal university Hackathon for national representation.",
    date: "September 2025",
    category: "National Contest",
    badge: "Top 3 MNNIT",
  },
  {
    id: 3,
    title: "Web Development Hackathon (Codesangam, MNNIT)",
    rank: "2nd Runner-up (3rd Position)",
    description: "Achieved 3rd position in official web development hackathon under Codesangam at MNNIT Allahabad.",
    date: "2024",
    category: "Hackathon",
    badge: "Podium Finish",
  },
  {
    id: 4,
    title: "Development Hackathon (Jadavpur University)",
    rank: "Semi-finalist (Top 20)",
    description: "Selected among top 20 teams out of 330+ participating teams in Development Hackathon at Jadavpur University.",
    date: "2024",
    category: "Hackathon",
    badge: "Top 6%",
  },
  {
    id: 5,
    title: "LeetCode Biweekly Contest",
    rank: "Global Rank 705",
    description: "Ranked 705 globally out of 31,000+ international competitive programmers in LeetCode Biweekly Contest.",
    date: "July 2024",
    category: "Competitive Programming",
    badge: "Global Top 2.2%",
  },
  {
    id: 6,
    title: "Flipkart Grid 7.0",
    rank: "Qualified Round 2",
    description: "Placed in the top 10% out of 1.6 lakh+ participants across India, advancing to Round 2.",
    date: "July 2025",
    category: "National Challenge",
    badge: "Top 10% of 160K+",
  },
];

export const NAV_LINKS = [
  { name: "Experience", href: "#experience" },
  { name: "Projects", href: "#projects" },
  { name: "Skills", href: "#skills" },
  { name: "Rankings", href: "#coding-profiles" },
  { name: "Awards", href: "#achievements" },
  { name: "About", href: "#about" },
  { name: "Contact", href: "#contact" },
];
